-- SE FOSSE UTILIZAR ESSE SCRIPT PARA GERAR AS TABELAS NO NA BASE H2 TERIA QUE MUDAR O NOME DO ARQUIVO PARA
    -- nome: data.sql
-- Pois aí o hibernate entende esse nome de arquivo, mapeia ele e gera as tabelas na base

-- *****QUANDO FOR CRIAR NO MYSQL TEM QUE USAR ESSES 2 COMANDOS
-- 1. CRIAR O DATABASE VENDAS
-- 2. ATIVAR O BANCO VENDAS CRIADO
-- *************************************************************

-- create database vendas;
-- use vendas;

-- *************************************************************

CREATE TABLE CLIENTE (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100),
    CPF VARCHAR(11)
);

CREATE TABLE PRODUTO (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    DESCRICAO VARCHAR(100),
    PRECO_UNITARIO NUMERIC(20,2)
);

CREATE TABLE PEDIDO (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    CLIENTE_ID INTEGER REFERENCES CLIENTE (ID),
    DATA_PEDIDO TIMESTAMP,
    STATUS VARCHAR(20),
    TOTAL NUMERIC(20,2)
);

CREATE TABLE ITEM_PEDIDO (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    PEDIDO_ID INTEGER REFERENCES PEDIDO (ID),
    PRODUTO_ID INTEGER REFERENCES PRODUTO (ID),
    QUANTIDADE INTEGER
);

CREATE TABLE USUARIO(
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    LOGIN VARCHAR(50),
    SENHA VARCHAR(255),
    ADMIN BOOL DEFAULT FALSE
);